RelA.WebUI/Models/TaskStatusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RelA.Domain.Entities;
using RelA.WebUI.Models.Filters;

namespace RelA.WebUI.Models
{
    public class TaskStatusViewModel : ViewModelBase<TaskStatus, TaskStatusFilter>
    {
    }
}

RelA.WebUI/Controllers/TaskStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RelA.Domain.Abstract;
using RelA.Domain.Entities;
using RelA.Domain.Concrete;
using RelA.WebUI.Models;

namespace RelA.WebUI.Controllers
{
    public class TaskStatusController : Controller
    {
        ITaskStatusRepository repository = null;

        public TaskStatusController(ITaskStatusRepository repo)
        {
            this.repository = repo;
        }

        public ActionResult Index()
        {
            TaskStatusViewModel model = new TaskStatusViewModel();
            model.Entity = repository.GetAll;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(TaskStatusViewModel model)
        {
            IQueryable<TaskStatus> query = repository.GetAll;

            if (model.Filter != null)
            {
                if (!string.IsNullOrWhiteSpace(model.Filter.Description))
                {
                    query = query.Where(w => w.Description.Contains(model.Filter.Description));
                }
            }

            model.Entity = query;

            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.Title = "Criar Novo Status";

            return View("Edit", new TaskStatus());
        }
            
        public ActionResult Edit(int TaskStatusID)
        {
            ViewBag.Title = "Editar Status";

            TaskStatus editTaskStatus = repository.GetAll.FirstOrDefault(w => w.TaskStatusID == TaskStatusID);

            if (editTaskStatus != null)
            {
                return View(editTaskStatus);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        
        [HttpPost]
        public ActionResult Edit(TaskStatus TaskStatus)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repository.Save(TaskStatus);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(TaskStatus);
                }
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Delete(int TaskStatusID)
        {
            repository.Delete(TaskStatusID);

            return RedirectToAction("Index");
        }
    }
}

RelA.WebUI/Views/TaskStatus/Edit.cshtml
@model RelA.Domain.Entities.TaskStatus
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        $(".color-picker").miniColors({
            letterCase: 'uppercase',
            change: function (hex, rgb) {
                
            }
        });
    });
</script>
<h2>
    @ViewBag.Title
</h2>
<div class="toolBar">
    @Html.ActionLink("Cancelar", "Index")
</div>
<hr />
@using (@Html.BeginForm("Edit", "TaskStatus"))
{
    @Html.HiddenFor(h=>h.TaskStatusID)
    @Html.EditorFor(e => e.Description) 
    <input type="hidden" name="color" class="color-picker" size="6" value="@Model.Color" />
    <br />
    <input type="submit" value="Salvar" class="actionButtons" /> 
}

RelA.WebUI/Views/TaskStatus/Index.cshtml
@model RelA.WebUI.Models.TaskStatusViewModel
@using RelA.Domain.Entities;
@{
    ViewBag.Title = "Consultar Tipos de Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Pesquisar Usuários</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="display-label">
        <label>
            Descrição</label>
    </div>
    <div class="display-field">
        @Html.TextBoxFor(m => m.Filter.Description)
    </div>
    
    <input type="submit" value="Pesquisar" class="actionButtons" />
}
<h3>
    Resultado</h3>
<div class="toolBar">@Html.ActionLink("Create a new Status", "Create")</div>
<hr />
@if (Model.Entity != null && Model.Entity.Count() > 0)
{
    <table class="Grid">
        <thead>
            <tr>
                <th>
                    Projeto
                </th>
                <th style="width: 100px">
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (TaskStatus item in Model.Entity)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Description, "Edit", new { TaskStatusID = item.TaskStatusID })
                    </td>
                    <td>
                        <div style="width:16px; height:16px; margin:auto; border:1px solid black; position:inherit; background-color:@item.Color">
                        </div>
                    </td>
                    <td class="buttons">
                        @using (Html.BeginForm("Delete", "TaskStatus"))
                        {
                            @Html.Hidden("TaskStatusID", item.TaskStatusID)
                            <input type="submit" value="Delete" class="actionButtons" onclick="return confirm('You really want to delete this user?');" @item.IsDefault : disabled="disabled" ? @string.Empty />
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>    
    <div class="pager">
        @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index", new { page = x }))
    </div>
}
else
{
    @:Nenhum registro encontrado!
}